export const edu = [
	{
		company: 'Codemy',
		link: 'https://codemy.uz/',
		role: 'Frontend Developer',
		date: 'January 2023 - April 2024',
		skills: [
			{ title: 'HTML' },
			{ title: 'CSS' },
			{ title: 'JavaScript' },
			{ title: 'React.js' },
			{ title: 'Redux' },
			{ title: 'Git / Github' },
			{ title: 'MUI' },
			{ title: 'Tailwindcss' },
			{ title: 'Computer Literacy' },
		],
		btn: [{ title: 'See Codemy', link: 'https://codemy.uz/' }],
		logo: '/codemy.jpg',
		desc: "Codemy orqali zamonaviy dasturlash texnologiyalarini noldan boshlab o‘rganish va amaliy loyihalar ustida ishlash imkoniyati mavjud. Mentorlar real ish sharoitiga yaqinlashtirilgan topshiriqlar asosida dars o‘tadilar. Bu yerda frontend va backend dasturchi sifatida rivojlanish mumkin va siz dasturlashni 0dan junior darajagacha o'rganing.",
	},
	{
		company: 'Sammi | Praktikum',
		link: 'https://www.sammi.ac/',
		role: 'Frontend | Fullstack Developer',
		date: 'June 2024 - November 2024',
		skills: [
			{ title: 'JavaScript' },
			{ title: 'TypeScript' },
			{ title: 'React.js' },
			{ title: 'Next.js' },
			{ title: 'Redux' },
			{ title: 'Git / Github' },
			{ title: 'CSS / SASS' },
			{ title: 'Tailwindcss' },
			{ title: 'CMS' },
			{ title: 'FireBase' },
			{ title: 'Telegrambot' },
			{ title: 'MongoDB' },
			{ title: 'SEO' },
		],

		btn: [
			{ title: 'See Sammi', link: 'https://sammi.ac/' },
			{ title: 'See Praktikum', link: 'https://praktikum.sammi.ac/' },
		],
		logo: '/sammi.svg',
		desc: `Sammi.ac — zamonaviy dasturlash texnologiyalarini o'rgatuvchi onlayn platforma. React, Next.js va Node.js kabi talabgir texnologiyalar bo'yicha chuqur va amaliy bilimlarni taqdim etadi. Mahalliy o'qituvchilar, xususan, Samar Badriddinovning tajribasi va aniq uslubi orqali o'quvchilar IT bozorida talab qilinadigan ko'nikmalarni o'rganishadi.
		`,
		sdesc: `Sammi Praktikum — IT sohasida real loyiha muhiti bilan ishlashni o'rgatuvchi amaliy dastur. Bu yerda o'quvchilar jamoaviy ishlash, mentorlik ko'magi va amaliy topshiriqlar orqali o'z bilim va tajribalarini mustahkamlaydilar. Bu dastur nafaqat nazariy bilim, balki IT bozorida muvaffaqiyatli ishlash uchun zarur bo'lgan ko'nikmalarni ham beradi.`,
	},
	{
		company: 'Amigoscode',
		link: 'https://www.amigoscode.com/',
		role: 'Git - Github Developer',
		date: 'December 2024 - 1-month',
		skills: [{ title: 'Git' }, { title: 'Github' }],
		btn: [{ title: 'See Amigoscode', link: 'https://codemy.uz/' }],
		logo: '/amigos.png',
		desc: 'Amigoscode — bu amaliy IT kurslari taqdim etuvchi xalqaro onlayn platforma. Platformada Java, Spring Boot, Git/GitHub, DevOps, AWS kabi texnologiyalar bo‘yicha chuqur va amaliy bilimlar beriladi. Ushbu kursda Git va GitHub bo‘yicha chuqur bilimlarni egallab, kod versiyalarini boshqarish va hamkorlikda ishlashni o‘rgandim.',
		certificate:
			'/certificates/certificate-of-completion-for-git-and-github-essentials.pdf',
		ctitle: 'Certificate:',
		cdesc: 'Certificate:',
	},
	{
		company: 'Geeksforgeeks',
		link: 'https://www.geeksforgeeks.org/',
		role: 'Backend | Frontend Developer',
		date: 'January 2018 - April 2018',
		logo: '/geks.png',
	},
];
